site_name: Cook In Home
nav:
  - Home: README.md
  - Starsystem:
      - 1 Star: starsystem/1Star.md
      - 2 Star: starsystem/2Star.md
      - 3 Star: starsystem/3Star.md
      - 4 Star: starsystem/4Star.md
      - 5 Star: starsystem/5Star.md
  - Tips:
      - Kitchen Prep:
          - 厨房准备: tips/厨房准备.md
          - 如何选择现在吃什么: tips/如何选择现在吃什么.md
          - 食材相克与禁忌: tips/食材相克与禁忌.md
      - 学习笔记:
          - 去腥: tips/learn/去腥.md
          - 学习凉拌: tips/learn/学习凉拌.md
          - 学习炒与煎: tips/learn/学习炒与煎.md
          - 学习焯水: tips/learn/学习焯水.md
          - 学习煮: tips/learn/学习煮.md
          - 学习腌: tips/learn/学习腌.md
          - 学习蒸: tips/learn/学习蒸.md
          - 微波炉: tips/learn/微波炉.md
          - 空气炸锅: tips/learn/空气炸锅.md
          - 食品安全: tips/learn/食品安全.md
          - 高压力锅: tips/learn/高压力锅.md
      - 高级技巧:
          - 辅料技巧: tips/advanced/辅料技巧.md
          - 高级专业术语: tips/advanced/高级专业术语.md
          - 糖色的炒制: tips/advanced/糖色的炒制.md
          - 油温判断技巧: tips/advanced/油温判断技巧.md
  - Dishes:
      - 蔬菜:
          - 拔丝土豆: dishes/vegetable_dish/拔丝土豆/拔丝土豆.md
          - 包菜炒鸡蛋粉丝: dishes/vegetable_dish/包菜炒鸡蛋粉丝/包菜炒鸡蛋粉丝.md
          - 白灼菜心: dishes/vegetable_dish/白灼菜心/白灼菜心.md
          - 菠菜炒鸡蛋: dishes/vegetable_dish/菠菜炒鸡蛋/菠菜炒鸡蛋.md
          - 炒滑蛋: dishes/vegetable_dish/炒滑蛋/炒滑蛋.md
          - 炒茄子: dishes/vegetable_dish/炒茄子.md
          - 炒青菜: dishes/vegetable_dish/炒青菜.md
          - 脆皮豆腐: dishes/vegetable_dish/脆皮豆腐.md
          - 地三鲜: dishes/vegetable_dish/地三鲜.md
          - 干锅花菜: dishes/vegetable_dish/干锅花菜/干锅花菜.md
          - 红烧冬瓜: dishes/vegetable_dish/红烧冬瓜/红烧冬瓜.md
          - 红烧茄子: dishes/vegetable_dish/红烧茄子.md
          - 虎皮青椒: dishes/vegetable_dish/虎皮青椒/虎皮青椒.md
          - 话梅煮毛豆: dishes/vegetable_dish/话梅煮毛豆/话梅煮毛豆.md
          - 鸡蛋羹: dishes/vegetable_dish/鸡蛋羹/鸡蛋羹.md
          - 蒸箱鸡蛋羹: dishes/vegetable_dish/鸡蛋羹/蒸箱鸡蛋羹.md
          - 微波炉鸡蛋羹: dishes/vegetable_dish/鸡蛋羹/微波炉鸡蛋羹.md
          - 金针菇日本豆腐煲: dishes/vegetable_dish/金针菇日本豆腐煲.md
          - 凉拌豆腐: dishes/vegetable_dish/凉拌豆腐.md
          - 凉拌黄瓜: dishes/vegetable_dish/凉拌黄瓜.md
          - 凉拌金针菇: dishes/vegetable_dish/凉拌金针菇.md
          - 凉拌木耳: dishes/vegetable_dish/凉拌木耳/凉拌木耳.md
          - 凉拌油麦菜: dishes/vegetable_dish/凉拌油麦菜.md
          - 莴笋叶煎饼: dishes/vegetable_dish/莴笋叶煎饼/莴笋叶煎饼.md
          - 蒜蓉空心菜: dishes/vegetable_dish/蒜蓉空心菜/蒜蓉空心菜.md
          - 蒜蓉西兰花: dishes/vegetable_dish/蒜蓉西兰花.md
          - 松仁玉米: dishes/vegetable_dish/松仁玉米.md
          - 素炒豆角: dishes/vegetable_dish/素炒豆角.md
          - 糖拌西红柿: dishes/vegetable_dish/糖拌西红柿/糖拌西红柿.md
          - 蚝油三鲜菇: dishes/vegetable_dish/蚝油三鲜菇/蚝油三鲜菇.md
          - 蚝油生菜: dishes/vegetable_dish/蚝油生菜.md
          - 脆皮豆腐: dishes/vegetable_dish/脆皮豆腐.md
          - 葫芦炒鸡蛋: dishes/vegetable_dish/西葫芦炒鸡蛋/西葫芦炒鸡蛋.md
          - 洋葱炒鸡蛋: dishes/vegetable_dish/洋葱炒鸡蛋/洋葱炒鸡蛋.md
          - 油醋爆蛋: dishes/vegetable_dish/油醋爆蛋.md
          - 芹菜拌茶树菇: dishes/vegetable_dish/芹菜拌茶树菇/芹菜拌茶树菇.md
          - 清炒花菜: dishes/vegetable_dish/清炒花菜.md
          - 清蒸南瓜: dishes/vegetable_dish/清蒸南瓜.md
          - 蒲烧茄子: dishes/vegetable_dish/蒲烧茄子.md
          - 上汤娃娃菜: dishes/vegetable_dish/上汤娃娃菜/上汤娃娃菜.md
          - 酸辣土豆丝: dishes/vegetable_dish/酸辣土豆丝.md
          - 西红柿炒鸡蛋: dishes/vegetable_dish/西红柿炒鸡蛋.md
          - 西红柿豆腐汤羹: dishes/vegetable_dish/西红柿豆腐汤羹/西红柿豆腐汤羹.md
          - 小炒藕丁: dishes/vegetable_dish/小炒藕丁/小炒藕丁.md
          - 烤茄子: dishes/vegetable_dish/烤茄子/烤茄子.md
          - 包菜炒鸡蛋粉丝: dishes/vegetable_dish/包菜炒鸡蛋粉丝/包菜炒鸡蛋粉丝.md
          - 拔丝土豆: dishes/vegetable_dish/拔丝土豆/拔丝土豆.md
          - 白灼菜心: dishes/vegetable_dish/白灼菜心/白灼菜心.md
          - 菠菜炒鸡蛋: dishes/vegetable_dish/菠菜炒鸡蛋/菠菜炒鸡蛋.md
          - 地三鲜: dishes/vegetable_dish/地三鲜.md
          - 红烧冬瓜: dishes/vegetable_dish/红烧冬瓜/红烧冬瓜.md
          - 红烧茄子: dishes/vegetable_dish/红烧茄子.md
          - 虎皮青椒: dishes/vegetable_dish/虎皮青椒/虎皮青椒.md
          - 话梅煮毛豆: dishes/vegetable_dish/话梅煮毛豆/话梅煮毛豆.md
          - 鸡蛋羹: dishes/vegetable_dish/鸡蛋羹/鸡蛋羹.md
          - 蒸箱鸡蛋羹: dishes/vegetable_dish/鸡蛋羹/蒸箱鸡蛋羹.md
          - 微波炉鸡蛋羹: dishes/vegetable_dish/鸡蛋羹/微波炉鸡蛋羹.md
      - 肉类:
          - 冷吃兔: dishes/meat_dish/冷吃兔.md
          - 咕噜肉: dishes/meat_dish/咕噜肉.md
          - 商芝肉: dishes/meat_dish/商芝肉.md
          - 小炒肉: dishes/meat_dish/小炒肉.md
          - 小酥肉: dishes/meat_dish/小酥肉.md
          - 杀猪菜: dishes/meat_dish/杀猪菜.md
          - 烤鸡翅: dishes/meat_dish/烤鸡翅.md
          - 粉蒸肉: dishes/meat_dish/粉蒸肉.md
          - 黄焖鸡: dishes/meat_dish/黄焖鸡.md
          - 可乐鸡翅: dishes/meat_dish/可乐鸡翅.md
          - 孜然牛肉: dishes/meat_dish/孜然牛肉.md
          - 带把肘子: dishes/meat_dish/带把肘子.md
          - 意式烤鸡: dishes/meat_dish/意式烤鸡.md
          - 椒盐排条: dishes/meat_dish/椒盐排条.md
          - 水煮肉片: dishes/meat_dish/水煮肉片.md
          - 番茄红酱: dishes/meat_dish/番茄红酱.md
          - 糖醋里脊: dishes/meat_dish/糖醋里脊.md
          - 肉饼炖蛋: dishes/meat_dish/肉饼炖蛋.md
          - 虎皮肘子: dishes/meat_dish/虎皮肘子.md
          - 蚂蚁上树: dishes/meat_dish/蚂蚁上树.md
          - 辣椒炒肉: dishes/meat_dish/辣椒炒肉.md
          - 香干肉丝: dishes/meat_dish/香干肉丝.md
          - 鱼香肉丝: dishes/meat_dish/鱼香肉丝.md
          - 麻辣香锅: dishes/meat_dish/麻辣香锅.md
          - 黄瓜炒肉: dishes/meat_dish/黄瓜炒肉.md
          - 香干芹菜炒肉: dishes/meat_dish/香干芹菜炒肉.md
          - 白菜猪肉炖粉条: dishes/meat_dish/白菜猪肉炖粉条.md
          - 猪肉烩酸菜: dishes/meat_dish/猪肉烩酸菜.md
          - 甜辣烤全翅: dishes/meat_dish/甜辣烤全翅.md
          - 萝卜炖羊排: dishes/meat_dish/萝卜炖羊排.md
          - 蒜苔炒肉末: dishes/meat_dish/蒜苔炒肉末.md
          - 乡村啤酒鸭: dishes/meat_dish/乡村啤酒鸭.md
          - 小米辣炒肉: dishes/meat_dish/小米辣炒肉.md
          - 尖椒炒牛肉: dishes/meat_dish/尖椒炒牛肉.md
          - 山西过油肉: dishes/meat_dish/山西过油肉.md
          - 洋葱炒猪肉: dishes/meat_dish/洋葱炒猪肉.md
          - 酱牛肉: dishes/meat_dish/酱牛肉.md
          - 红烧猪蹄: dishes/meat_dish/红烧猪蹄.md
          - 香煎五花肉: dishes/meat_dish/香煎五花肉/香煎五花肉.md
          - 干煸仔鸡: dishes/meat_dish/干煸仔鸡/干煸仔鸡.md
          - 新疆大盘鸡: dishes/meat_dish/新疆大盘鸡/新疆大盘鸡.md
          - 姜炒鸡: dishes/meat_dish/姜炒鸡/姜炒鸡.md
          - 姜葱捞鸡: dishes/meat_dish/姜葱捞鸡/姜葱捞鸡.md
          - 鱼香茄子: dishes/meat_dish/鱼香茄子/鱼香茄子.md
          - 口水鸡: dishes/meat_dish/口水鸡/口水鸡.md
          - 豆豉鲮鱼油麦菜: dishes/meat_dish/豆豉鲮鱼油麦菜/豆豉鲮鱼油麦菜.md
          - 红烧肉: dishes/meat_dish/红烧肉/简易红烧肉.md
          - 红烧肉（南派）: dishes/meat_dish/红烧肉/南派红烧肉.md
          - 荔枝肉: dishes/meat_dish/荔枝肉/荔枝肉.md
          - 酱排骨: dishes/meat_dish/酱排骨/酱排骨.md
          - 酱牛肉: dishes/meat_dish/酱牛肉/酱牛肉.md
          - 醉排骨: dishes/meat_dish/醉排骨/醉排骨.md
          - 冬瓜酿肉: dishes/meat_dish/冬瓜酿肉/冬瓜酿肉.md
          - 凉拌鸡丝: dishes/meat_dish/凉拌鸡丝/凉拌鸡丝.md
          - 咖喱肥牛: dishes/meat_dish/咖喱肥牛/咖喱肥牛.md
          - 奶酪培根通心粉: dishes/meat_dish/奶酪培根通心粉/奶酪培根通心粉.md
          - 湘祁米夫鸭: dishes/meat_dish/湘祁米夫鸭/湘祁米夫鸭.md
          - 梅菜扣肉: dishes/meat_dish/梅菜扣肉/梅菜扣肉.md
          - 枝竹羊腩煲: dishes/meat_dish/枝竹羊腩煲/枝竹羊腩煲.md
          - 香辣鸡爪煲: dishes/meat_dish/香辣鸡爪煲/香辣鸡爪煲.md
          - 广式萝卜牛腩: dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md
          - 荷兰豆炒腊肠: dishes/meat_dish/荷兰豆炒腊肠/荷兰豆炒腊肠.md
          - 黔式腊肠娃娃菜: dishes/meat_dish/黔式腊肠娃娃菜/黔式腊肠娃娃菜.md
          - 巴基斯坦牛肉咖喱: dishes/meat_dish/巴基斯坦牛肉咖喱/巴基斯坦牛肉咖喱.md
          - 西红柿土豆炖牛肉: dishes/meat_dish/西红柿土豆炖牛肉/西红柿土豆炖牛肉.md
          - 台式卤肉饭: dishes/meat_dish/台式卤肉饭/台式卤肉饭.md
          - 香菇滑鸡: dishes/meat_dish/香菇滑鸡/香菇滑鸡.md
          - 小炒鸡肝: dishes/meat_dish/小炒鸡肝/小炒鸡肝.md
          - 宫保鸡丁: dishes/meat_dish/宫保鸡丁/宫保鸡丁.md
          - 贵州辣子鸡: dishes/meat_dish/贵州辣子鸡/贵州辣子鸡.md
          - 麻婆豆腐: dishes/meat_dish/麻婆豆腐/麻婆豆腐.md
          - 徽派红烧肉: dishes/meat_dish/徽派红烧肉/徽派红烧肉.md
          - 小炒黄牛肉: dishes/meat_dish/小炒黄牛肉/小炒黄牛肉.md
          - 柱候牛腩: dishes/meat_dish/柱候牛腩/柱候牛腩.md
          - 香干芹菜炒肉: dishes/meat_dish/香干芹菜炒肉/香干芹菜炒肉.md
          - 芥末罗氏虾: dishes/meat_dish/芥末罗氏虾/芥末罗氏虾.md
          - 无骨鸡爪: dishes/meat_dish/无骨鸡爪/无骨鸡爪.md
          - 土豆炖排骨: dishes/meat_dish/土豆炖排骨/土豆炖排骨.md
          - 水煮牛肉: dishes/meat_dish/水煮牛肉/水煮牛肉.md
          - 瘦肉土豆片: dishes/meat_dish/瘦肉土豆片/瘦肉土豆片.md
          - 红烧猪蹄: dishes/meat_dish/红烧猪蹄/红烧猪蹄.md
          - 香煎五花肉: dishes/meat_dish/香煎五花肉/香煎五花肉.md
          - 农家一碗香: dishes/meat_dish/农家一碗香/农家一碗香.md
          - 湘祁米夫鸭: dishes/meat_dish/湘祁米夫鸭/湘祁米夫鸭.md
          - 荔枝肉: dishes/meat_dish/荔枝肉/荔枝肉.md
          - 酱排骨: dishes/meat_dish/酱排骨/酱排骨.md
          - 酱牛肉: dishes/meat_dish/酱牛肉/酱牛肉.md
          - 醉排骨: dishes/meat_dish/醉排骨/醉排骨.md
          - 冬瓜酿肉: dishes/meat_dish/冬瓜酿肉/冬瓜酿肉.md
          - 凉拌鸡丝: dishes/meat_dish/凉拌鸡丝/凉拌鸡丝.md
          - 咖喱肥牛: dishes/meat_dish/咖喱肥牛/咖喱肥牛.md
          - 奶酪培根通心粉: dishes/meat_dish/奶酪培根通心粉/奶酪培根通心粉.md
          - 梅菜扣肉: dishes/meat_dish/梅菜扣肉/梅菜扣肉.md
          - 枝竹羊腩煲: dishes/meat_dish/枝竹羊腩煲/枝竹羊腩煲.md
          - 香辣鸡爪煲: dishes/meat_dish/香辣鸡爪煲/香辣鸡爪煲.md
          - 广式萝卜牛腩: dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md
          - 荷兰豆炒腊肠: dishes/meat_dish/荷兰豆炒腊肠/荷兰豆炒腊肠.md
          - 黔式腊肠娃娃菜: dishes/meat_dish/黔式腊肠娃娃菜/黔式腊肠娃娃菜.md
          - 巴基斯坦牛肉咖喱: dishes/meat_dish/巴基斯坦牛肉咖喱/巴基斯坦牛肉咖喱.md
          - 西红柿土豆炖牛肉: dishes/meat_dish/西红柿土豆炖牛肉/西红柿土豆炖牛肉.md
          - 台式卤肉饭: dishes/meat_dish/台式卤肉饭/台式卤肉饭.md
          - 香菇滑鸡: dishes/meat_dish/香菇滑鸡/香菇滑鸡.md
          - 小炒鸡肝: dishes/meat_dish/小炒鸡肝/小炒鸡肝.md
          - 宫保鸡丁: dishes/meat_dish/宫保鸡丁/宫保鸡丁.md
          - 贵州辣子鸡: dishes/meat_dish/贵州辣子鸡/贵州辣子鸡.md
          - 麻婆豆腐: dishes/meat_dish/麻婆豆腐/麻婆豆腐.md
          - 徽派红烧肉: dishes/meat_dish/徽派红烧肉/徽派红烧肉.md
          - 小炒黄牛肉: dishes/meat_dish/小炒黄牛肉/小炒黄牛肉.md
          - 柱候牛腩: dishes/meat_dish/柱候牛腩/柱候牛腩.md
          - 香干芹菜炒肉: dishes/meat_dish/香干芹菜炒肉/香干芹菜炒肉.md
          - 芥末罗氏虾: dishes/meat_dish/芥末罗氏虾/芥末罗氏虾.md
          - 无骨鸡爪: dishes/meat_dish/无骨鸡爪/无骨鸡爪.md
          - 土豆炖排骨: dishes/meat_dish/土豆炖排骨/土豆炖排骨.md
          - 水煮牛肉: dishes/meat_dish/水煮牛肉/水煮牛肉.md
          - 瘦肉土豆片: dishes/meat_dish/瘦肉土豆片/瘦肉土豆片.md
          - 红烧猪蹄: dishes/meat_dish/红烧猪蹄/红烧猪蹄.md
          - 香煎五花肉: dishes/meat_dish/香煎五花肉/香煎五花肉.md
          - 农家一碗香: dishes/meat_dish/农家一碗香/农家一碗香.md
          - 湘祁米夫鸭: dishes/meat_dish/湘祁米夫鸭/湘祁米夫鸭.md
      - 海鲜:
          - 白灼虾: dishes/aquatic/白灼虾/白灼虾.md
          - 鳊鱼炖豆腐: dishes/aquatic/鳊鱼炖豆腐/鳊鱼炖豆腐.md
          - 蛏抱蛋: dishes/aquatic/蛏抱蛋/蛏抱蛋.md
          - 葱烧海参: dishes/aquatic/葱烧海参/葱烧海参.md
          - 葱油桂鱼: dishes/aquatic/葱油桂鱼/葱油桂鱼.md
          - 干煎阿根廷红虾: dishes/aquatic/干煎阿根廷红虾/干煎阿根廷红虾.md
          - 红烧鲤鱼: dishes/aquatic/红烧鲤鱼.md
          - 红烧鱼: dishes/aquatic/红烧鱼.md
          - 红烧鱼头: dishes/aquatic/红烧鱼头.md
          - 黄油煎虾: dishes/aquatic/黄油煎虾.md
          - 混合烤鱼: dishes/aquatic/混合烤鱼/烤鱼.md
          - 芥末黄油罗氏虾: dishes/aquatic/芥末黄油罗氏虾/芥末黄油罗氏虾.md
          - 咖喱炒蟹: dishes/aquatic/咖喱炒蟹.md
          - 鲤鱼炖白菜: dishes/aquatic/鲤鱼炖白菜/鲤鱼炖白菜.md
          - 清蒸鲈鱼: dishes/aquatic/清蒸鲈鱼/清蒸鲈鱼.md
          - 清蒸生蚝: dishes/aquatic/清蒸生蚝.md
          - 水煮鱼: dishes/aquatic/水煮鱼.md
          - 小龙虾: dishes/aquatic/小龙虾/小龙虾.md
          - 蒜香黄油虾: dishes/aquatic/蒜香黄油虾/蒜香黄油虾.md
          - 蒜蓉虾: dishes/aquatic/蒜蓉虾/蒜蓉虾.md
          - 油焖大虾: dishes/aquatic/油焖大虾/油焖大虾.md
          - 微波葱姜黑鳕鱼: dishes/aquatic/微波葱姜黑鳕鱼.md
          - 香煎翘嘴鱼: dishes/aquatic/香煎翘嘴鱼/香煎翘嘴鱼.md
          - 糖醋鲤鱼: dishes/aquatic/糖醋鲤鱼/糖醋鲤鱼.md
      - 早餐:
          - 牛奶燕麦: dishes/breakfast/牛奶燕麦.md
          - 茶叶蛋: dishes/breakfast/茶叶蛋.md
          - 桂圆红枣粥: dishes/breakfast/桂圆红枣粥.md
          - 微波炉荷包蛋: dishes/breakfast/微波炉荷包蛋.md
          - 水煮玉米: dishes/breakfast/水煮玉米.md
          - 手抓饼: dishes/breakfast/手抓饼.md
          - 溏心蛋: dishes/breakfast/溏心蛋.md
          - 完美水煮蛋: dishes/breakfast/完美水煮蛋.md
          - 燕麦鸡蛋饼: dishes/breakfast/燕麦鸡蛋饼.md
          - 蒸花卷: dishes/breakfast/蒸花卷.md
          - 吐司果酱: dishes/breakfast/吐司果酱.md
          - 微波炉蛋糕: dishes/breakfast/微波炉蛋糕.md
          - 苏格兰蛋: dishes/breakfast/苏格兰蛋/苏格兰蛋.md
          - 煎饺: dishes/breakfast/煎饺.md
          - 金枪鱼酱三明治: dishes/breakfast/金枪鱼酱三明治.md
          - 太阳蛋: dishes/breakfast/太阳蛋.md
          - 鸡蛋三明治: dishes/breakfast/鸡蛋三明治.md
          - 美式炒蛋: dishes/breakfast/美式炒蛋.md
          - 温泉蛋: dishes/breakfast/温泉蛋/温泉蛋.md
          - 蛋煎糍粑: dishes/breakfast/蛋煎糍粑.md
          - 蒸水蛋: dishes/breakfast/蒸水蛋.md
          - 空气炸锅面包片: dishes/breakfast/空气炸锅面包片.md
      - 主食:
          - 凉粉: dishes/staple/凉粉/凉粉.md
          - 烙饼: dishes/staple/烙饼/烙饼.md
          - 烧饼: dishes/staple/烧饼/芝麻烧饼.md
          - 米饭（煮锅蒸）: dishes/staple/米饭/煮锅蒸米饭.md
          - 米饭（电饭煲）: dishes/staple/米饭/电饭煲蒸米饭.md
          - 汤面: dishes/staple/汤面.md
          - 炒馍: dishes/staple/炒馍.md
          - 炒凉粉: dishes/staple/炒凉粉/炒凉粉.md
          - 炒方便面: dishes/staple/炒方便面.md
          - 炒米饭: dishes/staple/蛋炒饭.md
          - 炒年糕: dishes/staple/炒年糕.md
          - 炒河粉: dishes/staple/炒河粉.md
          - 酱拌荞麦面: dishes/staple/酱拌荞麦面/酱拌荞麦面.md
          - 酸辣蕨根粉: dishes/staple/酸辣蕨根粉.md
          - 蛋包饭: dishes/staple/蛋包饭.md
          - 蛋炒饭: dishes/staple/蛋炒饭.md
          - 肉蛋盖饭: dishes/staple/肉蛋盖饭.md
          - 热干面: dishes/staple/热干面.md
          - 螺蛳粉: dishes/staple/螺蛳粉.md
          - 韭菜盒子: dishes/staple/韭菜盒子.md
          - 麻油拌面: dishes/staple/麻油拌面.md
          - 葱油拌面: dishes/staple/葱油拌面.md
          - 老干妈拌面: dishes/staple/老干妈拌面.md
          - 手工水饺: dishes/staple/手工水饺.md
          - 中式馅饼: dishes/staple/中式馅饼/中式馅饼.md
          - 扬州炒饭: dishes/staple/扬州炒饭/扬州炒饭.md
          - 披萨饼皮: dishes/staple/披萨饼皮/披萨饼皮.md
          - 日式咖喱饭: dishes/staple/日式咖喱饭/日式咖喱饭.md
          - 基础牛奶面包: dishes/staple/基础牛奶面包/基础牛奶面包.md
          - 意式肉酱面: dishes/staple/意式肉酱面/意式肉酱面.md
          - 河南蒸面条: dishes/staple/河南蒸面条/河南蒸面条.md
          - 火腿饭团: dishes/staple/火腿饭团/火腿饭团.md
          - 韩式拌饭: dishes/staple/韩式拌饭/韩式拌饭.md
          - 微波炉腊肠煲仔饭: dishes/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.md
          - 电饭煲三文鱼炊饭: dishes/staple/电饭煲三文鱼炊饭/电饭煲三文鱼炊饭.md
          - 空气炸锅照烧鸡饭: dishes/staple/空气炸锅照烧鸡饭/空气炸锅照烧鸡饭.md
          - 日式肥牛丼饭: dishes/staple/日式肥牛丼饭/日式肥牛丼饭.md
          - 西红柿鸡蛋挂面: dishes/staple/西红柿鸡蛋挂面/西红柿鸡蛋挂面.md
          - 鲣鱼海苔玉米饭: dishes/staple/鲣鱼海苔玉米饭/鲣鱼海苔玉米饭.md
          - 陕西油泼面: dishes/staple/陕西油泼面/陕西油泼面.md
          - 蒸卤面: dishes/staple/蒸卤面.md
          - 醪糟小汤圆: dishes/staple/醪糟小汤圆.md
          - 煮泡面加蛋: dishes/staple/煮泡面加蛋.md
          - 茄子肉煎饼: dishes/staple/茄子肉煎饼/茄子肉煎饼.md
          - 老友猪肉粉: dishes/staple/老友猪肉粉/老友猪肉粉.md
          - 炒意大利面: dishes/staple/炒意大利面/炒意大利面.md
          - 麻辣减脂荞麦面: dishes/staple/麻辣减脂荞麦面.md
          - 豆角焖面: dishes/staple/豆角焖面/豆角焖面.md
      - 半成品:
          - 凉皮: dishes/semi-finished/凉皮.md
          - 炸薯条: dishes/semi-finished/炸薯条/炸薯条.md
          - 懒人蛋挞: dishes/semi-finished/懒人蛋挞/懒人蛋挞.md
          - 速冻汤圆: dishes/semi-finished/速冻汤圆/速冻汤圆.md
          - 速冻水饺: dishes/semi-finished/速冻水饺.md
          - 速冻馄饨: dishes/semi-finished/速冻馄饨.md
          - 半成品意面: dishes/semi-finished/半成品意面.md
          - 牛油火锅底料: dishes/semi-finished/牛油火锅底料.md
          - 空气炸锅羊排: dishes/semi-finished/空气炸锅羊排/空气炸锅羊排.md
          - 空气炸锅鸡翅中: dishes/semi-finished/空气炸锅鸡翅中/空气炸锅鸡翅中.md
      - 汤品:
          - 米粥: dishes/soup/米粥.md
          - 朱雀汤: dishes/soup/朱雀汤/朱雀汤.md
          - 羊肉汤: dishes/soup/羊肉汤/羊肉汤.md
          - 小米粥: dishes/soup/小米粥.md
          - 罗宋汤: dishes/soup/罗宋汤.md
          - 腊八粥: dishes/soup/腊八粥.md
          - 金针菇汤: dishes/soup/金针菇汤.md
          - 奶油蘑菇汤: dishes/soup/奶油蘑菇汤.md
          - 玉米排骨汤: dishes/soup/玉米排骨汤/玉米排骨汤.md
          - 生汆丸子汤: dishes/soup/生汆丸子汤.md
          - 紫菜蛋花汤: dishes/soup/紫菜蛋花汤.md
          - 陈皮排骨汤: dishes/soup/陈皮排骨汤.md
          - 陈皮排骨汤（子目录）: dishes/soup/陈皮排骨汤/陈皮排骨汤.md
          - 番茄牛肉蛋花汤: dishes/soup/番茄牛肉蛋花汤.md
          - 西红柿鸡蛋汤: dishes/soup/西红柿鸡蛋汤.md
          - 皮蛋瘦肉粥: dishes/soup/皮蛋瘦肉粥.md
          - 银耳莲子粥: dishes/soup/银耳莲子粥/银耳莲子粥.md
          - 昂刺鱼豆腐汤: dishes/soup/昂刺鱼豆腐汤/昂刺鱼豆腐汤.md
          - 勾芡香菇汤: dishes/soup/勾芡香菇汤/勾芡香菇汤.md
          - 菌菇炖乳鸽: dishes/soup/菌菇炖乳鸽/菌菇炖乳鸽.md
          - 排骨苦瓜汤: dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
      - 饮品:
          - B52轰炸机: dishes/drink/B52轰炸机.md
          - Mojito莫吉托: dishes/drink/Mojito莫吉托.md
          - 冰粉: dishes/drink/冰粉.md
          - 奶茶: dishes/drink/奶茶.md
          - 柠檬水: dishes/drink/柠檬水.md
          - 酸梅汤: dishes/drink/酸梅汤.md
          - 金汤力: dishes/drink/金汤力.md
          - 金菲士: dishes/drink/金菲士.md
          - 冬瓜茶: dishes/drink/冬瓜茶.md
          - 可乐桶: dishes/drink/可乐桶.md
          - 长岛冰茶: dishes/drink/长岛冰茶.md
          - 杨枝甘露: dishes/drink/杨枝甘露.md
          - 酒酿醪糟: dishes/drink/酒酿醪糟.md
          - 砂糖椰子冰沙: dishes/drink/砂糖椰子冰沙/砂糖椰子冰沙.md
          - 菠萝咖啡特调: dishes/drink/菠萝咖啡特调/菠萝咖啡特调.md
          - 奇异果菠菜特调: dishes/drink/奇异果菠菜特调/奇异果菠菜特调.md
          - 百香果橙子特调: dishes/drink/百香果橙子特调/百香果橙子特调.md
          - 海边落日: dishes/drink/海边落日.md
          - 泰国手标红茶: dishes/drink/泰国手标红茶/泰国手标红茶.md
          - 酸梅汤（半成品加工）: dishes/drink/酸梅汤（半成品加工）.md
          - 耙耙柑茶: dishes/drink/耙耙柑茶/耙耙柑茶.md
      - 调料:
          - 简易版炒糖色: dishes/condiment/简易版炒糖色.md
          - 油酥: dishes/condiment/油酥.md
          - 蒜香酱油: dishes/condiment/蒜香酱油.md
          - 炸串酱料: dishes/condiment/炸串酱料.md
          - 葱油: dishes/condiment/葱油.md
          - 油泼辣子: dishes/condiment/油泼辣子/油泼辣子.md
          - 草莓酱: dishes/condiment/草莓酱/草莓酱.md
          - 蔗糖糖浆: dishes/condiment/蔗糖糖浆/蔗糖糖浆.md
          - 糖醋汁: dishes/condiment/糖醋汁.md
      - 甜点:
          - 奥利奥冰淇淋: dishes/dessert/奥利奥冰淇淋/奥利奥冰淇淋.md
          - 烤箱版巴斯克芝士蛋糕: dishes/dessert/烤箱版巴斯克芝士蛋糕/烤箱版巴斯克芝士蛋糕.md
          - 龟苓膏: dishes/dessert/龟苓膏/龟苓膏.md
          - 咖啡椰奶冻: dishes/dessert/咖啡椰奶冻/咖啡椰奶冻.md
          - 炸鲜奶: dishes/dessert/炸鲜奶/炸鲜奶.md
          - 反沙芋头: dishes/dessert/反沙芋头/反沙芋头.md
          - 提拉米苏: dishes/dessert/提拉米苏/提拉米苏.md
          - 酸奶意式奶冻: dishes/dessert/酸奶意式奶冻/酸奶意式奶冻.md
          - 草莓冰淇淋: dishes/dessert/草莓冰淇淋/草莓冰淇淋.md
          - 无厨师机蜂蜜面包: dishes/dessert/无厨师机蜂蜜面包/无厨师机蜂蜜面包.md
          - 烤蛋挞: dishes/dessert/烤蛋挞/烤蛋挞.md
          - 红柚蛋糕: dishes/dessert/红柚蛋糕/红柚蛋糕.md
          - 英式司康: dishes/dessert/英式司康/英式司康.md
          - 芋泥雪媚娘: dishes/dessert/芋泥雪媚娘/芋泥雪媚娘.md
          - 魔芋蛋糕: dishes/dessert/魔芋蛋糕/魔芋蛋糕.md
          - 玛格丽特饼干: dishes/dessert/玛格丽特饼干/玛格丽特饼干.md
          - 雪花酥: dishes/dessert/雪花酥/雪花酥.md
          - 戚风蛋糕: dishes/dessert/戚风蛋糕/戚风蛋糕.md
      - 模板:
          - 示例菜: dishes/template/示例菜/示例菜.md